//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommercialEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientel
    {
        public clientel()
        {
            this.commandes = new HashSet<commandes>();
        }
    
        public string NO_CLIENT { get; set; }
        public string SOCIETE { get; set; }
        public string NOM_CL { get; set; }
        public string PRENOM_CL { get; set; }
        public string ADRESSE_CL { get; set; }
        public string VILLE_CL { get; set; }
        public string CODE_POST_CL { get; set; }
    
        public virtual ICollection<commandes> commandes { get; set; }
    }
}
