//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommercialEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commandes
    {
        public commandes()
        {
            this.detail_cde = new HashSet<detail_cde>();
        }
    
        public string NO_COMMAND { get; set; }
        public string NO_VENDEUR { get; set; }
        public string NO_CLIENT { get; set; }
        public System.DateTime DATE_CDE { get; set; }
        public string FACTURE { get; set; }
    
        public virtual clientel clientel { get; set; }
        public virtual vendeur vendeur { get; set; }
        public virtual ICollection<detail_cde> detail_cde { get; set; }
    }
}
