//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommercialEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compose
    {
        public string NO_COMPOSE { get; set; }
        public string NO_COMPOSANT { get; set; }
        public Nullable<int> QTE_COMPOSANT { get; set; }
    
        public virtual articles articles { get; set; }
        public virtual articles articles1 { get; set; }
    }
}
