//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommercialEntity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommercialEntities : DbContext
    {
        public CommercialEntities()
            : base("name=CommercialEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<articles> articles { get; set; }
        public DbSet<clientel> clientel { get; set; }
        public DbSet<commandes> commandes { get; set; }
        public DbSet<compose> compose { get; set; }
        public DbSet<detail_cde> detail_cde { get; set; }
        public DbSet<utilisateur> utilisateur { get; set; }
        public DbSet<vendeur> vendeur { get; set; }
    }
}
