//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommercialEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilisateur
    {
        public string idLogin { get; set; }
        public string motDePasse { get; set; }
        public string fonction { get; set; }
    
        public virtual vendeur vendeur { get; set; }
    }
}
