//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCommercialEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendeur
    {
        public vendeur()
        {
            this.commandes = new HashSet<commandes>();
            this.vendeur1 = new HashSet<vendeur>();
        }
    
        public string NO_VENDEUR { get; set; }
        public string NO_VEND_CHEF_EQ { get; set; }
        public string NOM_VEND { get; set; }
        public string PRENOM_VEND { get; set; }
        public System.DateTime DATE_EMBAU { get; set; }
        public string VILLE_VEND { get; set; }
        public decimal SALAIRE_VEND { get; set; }
        public decimal COMMISSION { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<commandes> commandes { get; set; }
        public virtual utilisateur utilisateur { get; set; }
        public virtual ICollection<vendeur> vendeur1 { get; set; }
        public virtual vendeur vendeur2 { get; set; }
    }
}
